version: 2.1
orbs:
  codecov: codecov/codecov@1.0.5
jobs:
  build:
    working_directory: ~/go-covid
    environment:
      GOROOT: ""
      PATH: "/usr/local/go/bin:/usr/local/go-covid/bin:~/.go-covid/bin:${PATH}"
      GOPATH: "${HOME}/.go-covid:/usr/local/go-covid:${HOME}/.go_project"
    docker:
      - image: circleci/golang:1.11
    steps:
      - checkout
      - run:
          name: "Create a temp directory for artifacts"
          command: |
            mkdir -p /tmp/artifacts
      - run:
          command: |
            go test -coverprofile=c.out
            go tool cover -html=c.out -o coverage.html
            mv coverage.html /tmp/artifacts
      - store_artifacts:
          path: /tmp/artifacts
      - codecov/upload:
          file: /tmp/artifacts/coverage.html
